tét/routes/admin.php
<?php
Route::group([
    'namespace' => 'Admin',
    'prefix' => 'admin',
    'as' => 'admin.'
],function (){
    Route::get('/', 'LoginController@index')
        ->middleware('admin.guest', 'preventBackHistory')
        ->name('login');
    Route::post('/login','LoginController@login')
        ->name('login.post');
    Route::post('/logout', 'LoginController@logout')
        ->name('logout');
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['check.login.admin', 'preventBackHistory']

],function (){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    /*Banner*/
    Route::group(['as' => 'banner.', 'prefix' => 'banner'], function (){
        Route::get('/','BannerController@index')->name('index');
        Route::get('/create','BannerController@create')->name('create');
        Route::post('/store','BannerController@store')->name('store');
        Route::get('/edit/{banner}','BannerController@edit')->name('edit');
        Route::post('/update/{banner}','BannerController@update')->name('update');
        Route::delete('/{banner}','BannerController@destroy')->name('destroy');
        Route::get('/search', 'BannerController@search')->name('search');
    });

    /*Brand*/
    Route::group(['as' => 'brand.', 'prefix' => 'brand'], function () {
        Route::get('/', 'BrandController@index')->name('index');
        Route::get('/create', 'BrandController@create')->name('create');
        Route::post('/store', 'BrandController@store')->name('store');
        Route::get('/edit/{brand}', 'BrandController@edit')->name('edit');
        Route::post('/update/{brand}', 'BrandController@update')->name('update');
        Route::delete('/{brand}', 'BrandController@destroy')->name('destroy');
        Route::get('/search', 'BrandController@search')->name('search');
    });
    /*Product*/
    Route::group(['as' => 'product.', 'prefix' => 'product'], function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/store', 'ProductController@store')->name('store');
        Route::get('/edit/{product}', 'ProductController@edit')->name('edit');
        Route::post('/product/{product}', 'ProductController@update')->name('product.update');
        Route::post('update/{product}', 'ProductController@update')
            ->name('update');
        Route::delete('/{product}', 'ProductController@destroy')->name('destroy');
        Route::get('/search', 'ProductController@search')->name('search');
    });
    /*Category*/
    Route::group(['as' => 'category.', 'prefix' => 'category'], function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/create', 'CategoryController@create')->name('create');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/edit/{category}', 'CategoryController@edit')->name('edit');
        Route::post('/update/{category}', 'CategoryController@update')->name('update');
        Route::delete('/{category}', 'CategoryController@destroy')->name('destroy');
        Route::get('/search', 'CategoryController@search')->name('search');
    });
    /*Shipping*/
    Route::get('/shipping','ShippingChargeController@index')->name('shipping_charge.index');
    Route::get('/shipping/create','ShippingChargeController@create')->name('shipping_charge.create');
    Route::post('/shipping/store','ShippingChargeController@store')->name('shipping_charge.store');
    Route::get('/shipping/edit/{shippingCharge}','ShippingChargeController@edit')
        ->name('shipping_charge.edit');
    Route::post('/shipping/update/{shippingCharge}','ShippingChargeController@update')
        ->name('shipping_charge.update');
    Route::delete('/shipping/{shippingCharge}','ShippingChargeController@destroy')
        ->name('shipping_charge.destroy');

    Route::get('/shipping/{slug}~{id}','ShippingController@editShipping')->name('edit.shipping');
    Route::post('/shipping/handle-edit/{id}','ShippingController@handleEditShipping')->name('handle.edit.shipping');
    Route::post('/shipping/delete-shipping','ShippingController@deleteShipping')->name('delete.shipping');

    /*Post*/
    Route::group(['as' => 'post.', 'prefix' => 'post'], function () {
        Route::get('/','PostController@index')->name('index');
        Route::get('/create','PostController@create')->name('create');
        Route::post('/store','PostController@store')->name('store');
        Route::get('/edit/{post}','PostController@edit')->name('edit');
        Route::post('/edit/{post}','PostController@update')->name('update');
        Route::delete('/{post}','PostController@destroy')->name('destroy');
    });

    /*Tags*/
    Route::group(['as' => 'tag.', 'prefix' => 'tag'], function () {
        Route::get('/','TagController@index')->name('index');
        Route::get('/create','TagController@create')->name('create');
        Route::post('/store','TagController@store')->name('store');
        Route::get('/edit/{tag}','TagController@edit')->name('edit');
        Route::post('/edit/{tag}','TagController@update')->name('update');
        Route::delete('/{tag}','TagController@destroy')->name('destroy');
        Route::get('/search','TagController@search')->name('search');
    });

    /*PostCategory*/
    Route::group(['as' => 'post_category.', 'prefix' => 'post-category'], function () {
        Route::get('/','PostCategoryController@index')->name('index');
        Route::get('/create','PostCategoryController@create')->name('create');
        Route::post('/store','PostCategoryController@store')->name('store');
        Route::get('/edit/{postCategory}','PostCategoryController@edit')->name('edit');
        Route::post('/edit/{postCategory}','PostCategoryController@update')->name('update');
        Route::delete('/{postCategory}','PostCategoryController@destroy')->name('destroy');
        Route::get('/search','PostCategoryController@search')->name('search');
    });
    /*Order*/
    Route::post('/order/{bill}','OrderController@update')->name('order.update');
    Route::get('/order','OrderController@getNewOrders')->name('order.new');
    Route::get('/order/delivery','OrderController@getDeliveryOrders')->name('order.delivery');
    Route::get('/order/done','OrderController@getDoneOrders')->name('order.done');
    Route::get('/add-order','OrderController@addOrder')->name('add.order');
    Route::post('/add-order','OrderController@handleOrder')->name('handle.add.order');
    Route::get('/order/{slug}~{id}','OrderController@editOrder')->name('edit.order');
    Route::post('/order/handle-edit/{id}','OrderController@handleEditOrder')->name('handle.edit.order');
    Route::get('/order/{bill}','OrderController@edit')->name('order.edit');

    /*Review*/
    Route::get('/review','ReviewController@index')->name('review');

    Route::get('/review/{slug}~{id}','ReviewController@editTag')->name('edit.review');
    Route::post('/review/handle-edit/{id}','ReviewController@handleEditTag')->name('handle.edit.review');
    Route::post('/review/delete-review','ReviewController@deleteTag')->name('delete.review');

    /*Coupon*/

    /*Users*/
    Route::get('/user','UserController@index')->name('users.index');
    Route::get('/add-users','UsersController@addUsers')->name('add.users');
    Route::post('/add-users','UsersController@handleUsers')->name('handle.add.users');
    Route::get('/users/{slug}~{id}','UsersController@editUsers')->name('edit.users');
    Route::post('/users/handle-edit/{id}','UsersController@handleEditUsers')->name('handle.edit.users');

    Route::group(['as' => 'statistic.'], function () {
        Route::get('/sale/{date?}', 'StatisticController@sale')->name('sale');
        Route::get('/revenue/{date?}', 'StatisticController@reportRevenue')->name('revenue');
        Route::get('/warning-product', 'StatisticController@warningProduct')->name('warning_product');
    });
});

tét/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'as' => 'fr.',
    'namespace' => 'Frontend',
], function () {
    Route::get('/category/{slug}~{id}', 'ProductController@getProductsBelongCategory')
        ->name('category.product');
    Route::get('/postcategory/{id}', 'PostController@getPostssBelongCategory')
        ->name('postcategory.product');
    Route::get('/post', 'PostController@index')
        ->name('post.index');
    Route::get('/post/{slug}~{id}', 'PostController@show')
        ->name('post.show');
    Route::get('/brand/{slug}~{id}', 'ProductController@getProductsBelongBrand')
        ->name('brand.product');
    Route::get('/{slug}~{id}', 'ProductController@show')
        ->name('product.show');
    Route::post('/product/increase', 'ProductController@increaseProduct')
        ->middleware('auth')
        ->name('product.increase_product');
    Route::post('/product/decrease', 'ProductController@decreaseProduct')
        ->middleware('auth')
        ->name('product.decrease_product');
    Route::get('/', 'FrontendController@index')->name('home');
    Route::get('/bill', 'BillController@show')
        ->name('bill');
    Route::get('/bill/detail/{id}', 'BillController@showDetail')
        ->name('bill.detail');
    Route::get('/search', 'ProductController@getSearch')
        ->name('searchproduct');
    Route::get('/cart', 'CartController@index')
        ->middleware('auth')
        ->name('cart');
    Route::post('/cart/add-product', 'CartController@addProduct')
        ->middleware('auth')
        ->name('cart.add_product');
    Route::post('/cart/increase', 'CartController@increaseProduct')
        ->middleware('auth')
        ->name('cart.increase_product');
    Route::post('/cart/decrease', 'CartController@decreaseProduct')
        ->middleware('auth')
        ->name('cart.decrease_product');
    Route::delete('/cart/delete', 'CartController@deleteProduct')
        ->middleware('auth')
        ->name('cart.delete_product');
    Route::post('/cart/checkout', 'CartController@checkout')
        ->middleware('auth')
        ->name('cart.checkout');
    Route::post('cart/overview-bill', 'CartController@overviewBill')
        ->middleware('can:bill')
        ->name('cart.overview_bill');
    Route::get('/check-out', 'CheckoutController@index')->name('check.out');
    Route::get('/register', 'RegisterController@index')->name('reegisgister');
    Route::group(['namespace' => 'Auth', 'as' => 'auth.'], function () {
        Route::get('/login', 'LoginController@showLoginForm')
            ->name('login');
        Route::post('/login', 'LoginController@login')
            ->name('login');
        Route::get('/logout', 'LoginController@logout')
            ->name('logout');
        Route::get('/register', 'RegisterController@showRegistrationForm')
            ->name('register');
        Route::post('/register', 'RegisterController@register')
            ->name('register');
    });

    Route::get('/provinces', 'ProvinceController@list')
        ->name('province.list');
    Route::get('/districts', 'DistrictController@list')
        ->name('district.list');
    Route::get('/wards', 'WardController@list')
        ->name('ward.list');
    Route::get('/shipping-charge/fee', 'ShippingChargeController@getFee')
        ->name('shipping_charge.get_fee');
    Route::get('/contact', 'ContactController@contact')
        ->name('contact.index');
    Route::post('/contact', 'ContactController@send')
        ->name('contact.send');
    Route::get('/about', 'AboutController@index')
        ->name('about.index');

});

tét/app/Http/Controllers/Admin/BrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use voku\helper\AntiXSS;
use App\Http\Requests\StoreBrandPost;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\UpdateStoreBrandPost;
use App\Model\Brand;
class BrandController extends Controller
{
    const LIMITED_ROW =5;
    public function index(Request $request, AntiXSS $antiXSS)
    {
        $data =[];
        $data['listBrands'] = DB::table('brands')
        ->paginate(self::LIMITED_ROW);
        return view('admin.brand.list',$data);
    }
    public function create()
    {
        return view('admin.brand.create');
    }
    public function store(StoreBrandPost $request,AntiXSS $xss)
    {
        $nameBrand = $request->nameBrand;
        $nameBrand = $xss->xss_clean($nameBrand);
        $slug =Str::slug($nameBrand,'-');
        $descBrand = $request->descBrand;

        $insert = DB::table('brands')->insert([
            'name' => $nameBrand,
            'slug' => $slug,
            'description' => $descBrand,
            'status' => 1,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => null
         ]);
         
         if($insert){
            Alert::success('Cập nhật thành công!');
            return redirect(route('admin.brand.index'));
         } else {
            Alert::error('Cập nhật thất bại!');
            return redirect(route('admin.brand.create'));
         }
    }
    public function edit(Request $request, Brand $brand)
    {
        return view('admin.brand.edit', compact('brand'));
    }
    public function update(UpdateStoreBrandPost $request,Brand $brand)
    {
        $nameBrand = $request->nameBrand;
        $descBrand = $request->descBrand;
        $slug =Str::slug($nameBrand,'-');
        $status = $request->status;
        if ($brand->update([
            'name' => $nameBrand,
            'slug' => $slug,
            'description' => $descBrand,
            'status' => $status,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => null
        ])) {
            Alert::success('Cập nhật thành công!');
            return redirect()->route('admin.brand.index');
        }
        Alert::error('Cập nhật thất bại!');
        return redirect()->route('admin.brand.edit',$brand->id);

    }

    public function destroy(Brand $brand)
    {
        if($brand->products()->count())
        {
            Alert::error('Bạn không được phép xóa');
        }
        else if ($brand->delete()) {
            Alert::success('Xóa thành công!');
        }
        else {
                Alert::error('Xóa không thành công!');
        }
        return redirect()->route('admin.brand.index');
    }

    public function search()
    {
        $listBrands = Brand::where('name', 'like', '%' . request()->search . '%')
        ->paginate(self::LIMITED_ROW);
        return view('admin.brand.list')->with('listBrands', $listBrands);
    }

}

tét/app/Http/Controllers/Frontend/BrandController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    public function getProductBelongBrand(){
        return view('frontend.cart.index');
    }
}

tét/resources/views/admin/brand/create.blade.php
@extends('admin.admin-layout')
@section('content')

    <div class="card cart-container shadow mb-4">
        <!-- Page Heading -->
        <div class="card-header mb-4">

        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Thêm thương hiệu</h1>
            <a href="{{route('admin.brand.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-list fa-sm text-white-50"></i> Danh sách thương hiệu</a>
        </div>

        </div>
        <!-- Content Row -->
        <div class="card-body">
        <div class="row">
            <div class="col-12 col-sm-12 col-lg-12 col-xl-12 col-md-12 mb-4">
                <form action="{{route('admin.brand.store')}}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="nameBrand">Tên thương hiệu</label>
                        <input class="form-control" value="{{old('nameBrand')}}" type="text" id="nameBrand" name="nameBrand"
                         />
                        @error('nameBrand')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="descBrand">Mô tả</label>
                        <textarea class="form-control" value="{{old('descBrand')}}" id="descBrand" name="descBrand" rows="8"></textarea>
                        @error('descBrand')
                        <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <button class="btn btn-primary" type="submit"> Lưu</button>
                    <button type="reset" class="btn btn-warning">Quay lại
                    </button>
                </form>
            </div>
        </div>
        </div>
    </div>



@endsection

tét/resources/views/admin/brand/edit.blade.php
@extends('admin.admin-layout')

@section('content')
<div class="card cart-container shadow mb-4">
    <!-- Page Heading -->
    <div class="card-header mb-4">

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Sửa thương hiệu:{{ $brand->name }}</h1>
        <a href="{{route('admin.brand.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-list fa-sm text-white-50"></i> Danh sách thương hiệu</a>
    </div>

    </div>
    <!-- Content Row -->
    <div class="card-body">
    <div class="row">
        <div class="col-12 col-sm-12 col-lg-12 col-xl-12 col-md-12 mb-4">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @if(!empty($message))
            <div class="alert alert-danger">
                {{ $message }}
            </div>
            @endif

            <form action="{{route('admin.brand.update',$brand->id)}}" method="post">
                @csrf
                <div class="form-group">
                    <label for="nameBrand">Tên thương hiệu</label>
                    <input  class="form-control"
                    value="{{$brand->name}}"
                    type="text"
                    id="nameBrand"
                    name="nameBrand"/>
                </div>
                <div class="form-group">
                    <label for="descBrand">Mô tả</label>
                    <textarea class="form-control" id="descBrand" name="descBrand" rows="8">{!! $brand->description !!}</textarea>
                </div>
                <div class="form-group">
                    <label for="status">Trạng thái</label>
                    <select name="status" id="status" class="form-control">
                        <option value="1" {{$brand->status == 1 ? 'selected' : ''}}>Hoạt động</option>
                        <option value="0" {{$brand->status == 0 ? 'selected' : ''}}>Không hoạt động</option>
                    </select>
                </div>
                <button class="btn btn-primary" type="submit"> Cập nhật </button>
                <button type="reset" class="btn btn-warning">Quay lại
                </button>
            </form>
        </div>
    </div>
    </div>
</div>
@endsection

tét/resources/views/admin/brand/list.blade.php
@extends('admin.admin-layout')
@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <div class="row">
                <div class="col-md-4">
                    <h4 class="m-0 font-weight-bold text-primary float-left">Danh mục Thương hiệu</h4>
                </div>

                <div class="col-md-4">
                    <form role="search" method="GET" id="searchform" action="{{route('admin.brand.search')}}">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border small js-keyword-brand"
                                placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" name="search" value="">
                            <div class="input-group-append">
                                <button class="btn btn-primary js-search-brand" type="submit"  value="">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                </div>
                <div class="col-md-4 ">
                    <a href="{{ route('admin.brand.create')}}"
                        class="d-none d-sm-inline-block btn btn-primary shadow-sm float-right" data-toggle="tooltip"
                        data-placement="bottom" title="Thêm thương hiệu"><i
                        class="fas fa-plus-circle fa-sm text-white-50"></i>  Thêm thương hiệu</a>
             </div>
            </div>
        </div>
        <!--table-->

        <div class="card-body">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <td width="5%">ID</td>
                        <th width="5%">Tên thương hiệu</th>
                        <th width="5%">Mô tả</th>
                        <th width="10%">Tình trạng</th>
                        <th colspan="2" width="10%">Hành động</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td>ID</td>
                        <th> Tên thương hiệu</th>
                        <th>Mô tả</th>
                        <th>Tình trạng</th>
                        <th colspan="2" width="10%">Hành động</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach ($listBrands as $key => $item)
                        <tr>
                            <td>{{ $item->id }}</td>
                            <td>
                                <a href="{{ route('admin.brand.edit', ['brand' => $item->id]) }}">
                                    {{ $item->name }}
                                </a>
                            </td>
                            <td>{!! $item->description !!}</td>
                            <td>

                                @if($item->status== 1)
                                <span class="badge badge-success">Hoạt động</span>
                                @else
                                <span class="badge badge-warning">Ngừng hoạt động</span>
                                @endif
                            </td>
                            <td>
                                <a href="{{route('admin.brand.edit', $item->id)}}"
                                   class="btn btn-primary btn-sm float-left mr-1"
                                   style="height:30px; width:30px;border-radius:50%"
                                   data-toggle="tooltip" title="edit"
                                   data-placement="bottom"><i
                                        class="fas fa-edit"></i></a>
                                <form
                                    action="{{route('admin.brand.destroy',$item->id)}}"
                                    method="post">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger btn-sm"
                                            style="height:30px; width:30px;border-radius:50%"
                                            type="submit"
                                            data-toggle="tooltip"
                                            data-placement="bottom"
                                            title="Delete"><i
                                            class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="text-center">
                {{-- Hien thi phan trang --}}
               {{ $listBrands->links() }}
            </div>

        </div>

    </div>
@endsection
@push('javascripts')
  <script type="text/javascript">
    var urlAjax = "{{ route('admin.brand.destroy',['brand=> $item->id']) }}";

</script>
    <script type="text/javascript" src="{{ asset('backend/js/admin-brands.js') }}"></script>

@endpush