tét/routes/admin.php
<?php
Route::group([
    'namespace' => 'Admin',
    'prefix' => 'admin',
    'as' => 'admin.'
],function (){
    Route::get('/', 'LoginController@index')
        ->middleware('admin.guest', 'preventBackHistory')
        ->name('login');
    Route::post('/login','LoginController@login')
        ->name('login.post');
    Route::post('/logout', 'LoginController@logout')
        ->name('logout');
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['check.login.admin', 'preventBackHistory']

],function (){
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    /*Banner*/
    Route::group(['as' => 'banner.', 'prefix' => 'banner'], function (){
        Route::get('/','BannerController@index')->name('index');
        Route::get('/create','BannerController@create')->name('create');
        Route::post('/store','BannerController@store')->name('store');
        Route::get('/edit/{banner}','BannerController@edit')->name('edit');
        Route::post('/update/{banner}','BannerController@update')->name('update');
        Route::delete('/{banner}','BannerController@destroy')->name('destroy');
        Route::get('/search', 'BannerController@search')->name('search');
    });

    /*Brand*/
    Route::group(['as' => 'brand.', 'prefix' => 'brand'], function () {
        Route::get('/', 'BrandController@index')->name('index');
        Route::get('/create', 'BrandController@create')->name('create');
        Route::post('/store', 'BrandController@store')->name('store');
        Route::get('/edit/{brand}', 'BrandController@edit')->name('edit');
        Route::post('/update/{brand}', 'BrandController@update')->name('update');
        Route::delete('/{brand}', 'BrandController@destroy')->name('destroy');
        Route::get('/search', 'BrandController@search')->name('search');
    });
    /*Product*/
    Route::group(['as' => 'product.', 'prefix' => 'product'], function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::post('/store', 'ProductController@store')->name('store');
        Route::get('/edit/{product}', 'ProductController@edit')->name('edit');
        Route::post('/product/{product}', 'ProductController@update')->name('product.update');
        Route::post('update/{product}', 'ProductController@update')
            ->name('update');
        Route::delete('/{product}', 'ProductController@destroy')->name('destroy');
        Route::get('/search', 'ProductController@search')->name('search');
    });
    /*Category*/
    Route::group(['as' => 'category.', 'prefix' => 'category'], function () {
        Route::get('/', 'CategoryController@index')->name('index');
        Route::get('/create', 'CategoryController@create')->name('create');
        Route::post('/create', 'CategoryController@store')->name('store');
        Route::get('/edit/{category}', 'CategoryController@edit')->name('edit');
        Route::post('/update/{category}', 'CategoryController@update')->name('update');
        Route::delete('/{category}', 'CategoryController@destroy')->name('destroy');
        Route::get('/search', 'CategoryController@search')->name('search');
    });
    /*Shipping*/
    Route::get('/shipping','ShippingChargeController@index')->name('shipping_charge.index');
    Route::get('/shipping/create','ShippingChargeController@create')->name('shipping_charge.create');
    Route::post('/shipping/store','ShippingChargeController@store')->name('shipping_charge.store');
    Route::get('/shipping/edit/{shippingCharge}','ShippingChargeController@edit')
        ->name('shipping_charge.edit');
    Route::post('/shipping/update/{shippingCharge}','ShippingChargeController@update')
        ->name('shipping_charge.update');
    Route::delete('/shipping/{shippingCharge}','ShippingChargeController@destroy')
        ->name('shipping_charge.destroy');

    Route::get('/shipping/{slug}~{id}','ShippingController@editShipping')->name('edit.shipping');
    Route::post('/shipping/handle-edit/{id}','ShippingController@handleEditShipping')->name('handle.edit.shipping');
    Route::post('/shipping/delete-shipping','ShippingController@deleteShipping')->name('delete.shipping');

    /*Post*/
    Route::group(['as' => 'post.', 'prefix' => 'post'], function () {
        Route::get('/','PostController@index')->name('index');
        Route::get('/create','PostController@create')->name('create');
        Route::post('/store','PostController@store')->name('store');
        Route::get('/edit/{post}','PostController@edit')->name('edit');
        Route::post('/edit/{post}','PostController@update')->name('update');
        Route::delete('/{post}','PostController@destroy')->name('destroy');
    });

    /*Tags*/
    Route::group(['as' => 'tag.', 'prefix' => 'tag'], function () {
        Route::get('/','TagController@index')->name('index');
        Route::get('/create','TagController@create')->name('create');
        Route::post('/store','TagController@store')->name('store');
        Route::get('/edit/{tag}','TagController@edit')->name('edit');
        Route::post('/edit/{tag}','TagController@update')->name('update');
        Route::delete('/{tag}','TagController@destroy')->name('destroy');
        Route::get('/search','TagController@search')->name('search');
    });

    /*PostCategory*/
    Route::group(['as' => 'post_category.', 'prefix' => 'post-category'], function () {
        Route::get('/','PostCategoryController@index')->name('index');
        Route::get('/create','PostCategoryController@create')->name('create');
        Route::post('/store','PostCategoryController@store')->name('store');
        Route::get('/edit/{postCategory}','PostCategoryController@edit')->name('edit');
        Route::post('/edit/{postCategory}','PostCategoryController@update')->name('update');
        Route::delete('/{postCategory}','PostCategoryController@destroy')->name('destroy');
        Route::get('/search','PostCategoryController@search')->name('search');
    });
    /*Order*/
    Route::post('/order/{bill}','OrderController@update')->name('order.update');
    Route::get('/order','OrderController@getNewOrders')->name('order.new');
    Route::get('/order/delivery','OrderController@getDeliveryOrders')->name('order.delivery');
    Route::get('/order/done','OrderController@getDoneOrders')->name('order.done');
    Route::get('/add-order','OrderController@addOrder')->name('add.order');
    Route::post('/add-order','OrderController@handleOrder')->name('handle.add.order');
    Route::get('/order/{slug}~{id}','OrderController@editOrder')->name('edit.order');
    Route::post('/order/handle-edit/{id}','OrderController@handleEditOrder')->name('handle.edit.order');
    Route::get('/order/{bill}','OrderController@edit')->name('order.edit');

    /*Review*/
    Route::get('/review','ReviewController@index')->name('review');

    Route::get('/review/{slug}~{id}','ReviewController@editTag')->name('edit.review');
    Route::post('/review/handle-edit/{id}','ReviewController@handleEditTag')->name('handle.edit.review');
    Route::post('/review/delete-review','ReviewController@deleteTag')->name('delete.review');

    /*Coupon*/

    /*Users*/
    Route::get('/user','UserController@index')->name('users.index');
    Route::get('/add-users','UsersController@addUsers')->name('add.users');
    Route::post('/add-users','UsersController@handleUsers')->name('handle.add.users');
    Route::get('/users/{slug}~{id}','UsersController@editUsers')->name('edit.users');
    Route::post('/users/handle-edit/{id}','UsersController@handleEditUsers')->name('handle.edit.users');

    Route::group(['as' => 'statistic.'], function () {
        Route::get('/sale/{date?}', 'StatisticController@sale')->name('sale');
        Route::get('/revenue/{date?}', 'StatisticController@reportRevenue')->name('revenue');
        Route::get('/warning-product', 'StatisticController@warningProduct')->name('warning_product');
    });
});

tét/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//    return view('welcome');
//});
Route::group([
    'as' => 'fr.',
    'namespace' => 'Frontend',
], function () {
    Route::get('/category/{slug}~{id}', 'ProductController@getProductsBelongCategory')
        ->name('category.product');
    Route::get('/postcategory/{id}', 'PostController@getPostssBelongCategory')
        ->name('postcategory.product');
    Route::get('/post', 'PostController@index')
        ->name('post.index');
    Route::get('/post/{slug}~{id}', 'PostController@show')
        ->name('post.show');
    Route::get('/brand/{slug}~{id}', 'ProductController@getProductsBelongBrand')
        ->name('brand.product');
    Route::get('/{slug}~{id}', 'ProductController@show')
        ->name('product.show');
    Route::post('/product/increase', 'ProductController@increaseProduct')
        ->middleware('auth')
        ->name('product.increase_product');
    Route::post('/product/decrease', 'ProductController@decreaseProduct')
        ->middleware('auth')
        ->name('product.decrease_product');
    Route::get('/', 'FrontendController@index')->name('home');
    Route::get('/bill', 'BillController@show')
        ->name('bill');
    Route::get('/bill/detail/{id}', 'BillController@showDetail')
        ->name('bill.detail');
    Route::get('/search', 'ProductController@getSearch')
        ->name('searchproduct');
    Route::get('/cart', 'CartController@index')
        ->middleware('auth')
        ->name('cart');
    Route::post('/cart/add-product', 'CartController@addProduct')
        ->middleware('auth')
        ->name('cart.add_product');
    Route::post('/cart/increase', 'CartController@increaseProduct')
        ->middleware('auth')
        ->name('cart.increase_product');
    Route::post('/cart/decrease', 'CartController@decreaseProduct')
        ->middleware('auth')
        ->name('cart.decrease_product');
    Route::delete('/cart/delete', 'CartController@deleteProduct')
        ->middleware('auth')
        ->name('cart.delete_product');
    Route::post('/cart/checkout', 'CartController@checkout')
        ->middleware('auth')
        ->name('cart.checkout');
    Route::post('cart/overview-bill', 'CartController@overviewBill')
        ->middleware('can:bill')
        ->name('cart.overview_bill');
    Route::get('/check-out', 'CheckoutController@index')->name('check.out');
    Route::get('/register', 'RegisterController@index')->name('reegisgister');
    Route::group(['namespace' => 'Auth', 'as' => 'auth.'], function () {
        Route::get('/login', 'LoginController@showLoginForm')
            ->name('login');
        Route::post('/login', 'LoginController@login')
            ->name('login');
        Route::get('/logout', 'LoginController@logout')
            ->name('logout');
        Route::get('/register', 'RegisterController@showRegistrationForm')
            ->name('register');
        Route::post('/register', 'RegisterController@register')
            ->name('register');
    });

    Route::get('/provinces', 'ProvinceController@list')
        ->name('province.list');
    Route::get('/districts', 'DistrictController@list')
        ->name('district.list');
    Route::get('/wards', 'WardController@list')
        ->name('ward.list');
    Route::get('/shipping-charge/fee', 'ShippingChargeController@getFee')
        ->name('shipping_charge.get_fee');
    Route::get('/contact', 'ContactController@contact')
        ->name('contact.index');
    Route::post('/contact', 'ContactController@send')
        ->name('contact.send');
    Route::get('/about', 'AboutController@index')
        ->name('about.index');

});

tét/app/Http/Controllers/Frontend/AboutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Mail\Inquiry;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use RealRashid\SweetAlert\Facades\Alert;

class AboutController extends Controller
{
    public function index(){
        return view('frontend.about');
    }
}

tét/app/Http/Controllers/Frontend/BillController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Model\Cart;
use Illuminate\Support\Facades\Auth;

class BillController extends Controller
{
    public function show(){
        $carts = Cart::where('user_id', Auth::id())->whereHas('bill')->get();
        return view('frontend.bills.show',compact('carts'));
    }
    public function showDetail(){
        $cart = Cart::findOrFail(request()->id);
        return view('frontend.bills.showDetail',compact('cart'));
    }
}

tét/app/Http/Controllers/Frontend/BrandController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    public function getProductBelongBrand(){
        return view('frontend.cart.index');
    }
}

tét/app/Http/Controllers/Frontend/CheckoutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CheckoutController extends Controller
{
    public function index(){
        return view('frontend.checkout.index');    
    }    
}

tét/app/Http/Controllers/Frontend/ContactController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Mail\Inquiry;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

class ContactController extends Controller
{
    public function contact(){
        if(!Auth::user()) {
            return redirect()->route('fr.auth.login');
        }
        return view('frontend.contact');
    }

    public function send()
    {
        $inquiryPersonName = request()->name;
        $inquiryPersonEmail = request()->email;
        $message = request()->message;
        if ($message && $inquiryPersonName && $inquiryPersonEmail) {
            Mail::to(config('mail.address'))
                ->send(new Inquiry($inquiryPersonName, $inquiryPersonEmail, $message));
            Alert::success('Gửi contact thành công!!');
        }else{
            Alert::error('Vui lòng điền đầy đủ thông tin!!');
        }
        return redirect()->route('fr.contact.index');
    }
}

tét/app/Http/Controllers/Frontend/DistrictController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Model\Bill;

use App\Http\Controllers\Controller;
use App\Model\Cart;
use App\Model\District;
use App\Model\Product;
use App\Model\Province;
use App\Services\ProductService;
use App\Traits\InventoryTrait;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use RealRashid\SweetAlert\Facades\Alert;

class DistrictController extends Controller
{
    public function list()
    {
        $provinceId = request()->province_id;
        if (isset($provinceId)) {
            $districts = Province::findOrFail($provinceId)->districts;
        }else {
            $districts = District::all();
        }
        return response()->json([
            'districts' => $districts,
        ], 200);
    }
}

tét/app/Http/Controllers/Frontend/FrontendController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Model\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class FrontendController extends Controller
{
    public function index()
    {
        $today = date('Y-m-d H:i:s');
        $yesterday = date('Y-m-d H:i:s', strtotime('-30days'));
        $pagination = request()->pagination ?? config('app.pagination');
        $orderType = request()->order_type ?? '';
        //khong để mặc định
        $newProducts = DB::table('products')
            ->where('status', Product::ACTIVE)
            ->whereBetween('created_at', [$yesterday, $today]);
        
        if ($orderType) {
            $newProducts->orderBy('price', $orderType);
        }
        $newProducts = $newProducts->paginate($pagination);
        return view('frontend.home.index', compact('newProducts'));
    }
}

tét/app/Http/Controllers/Frontend/PostController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Model\Post;
use App\Model\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Model\PostCategory;
use App\Model\Tag;
class PostController extends Controller
{
    public function index()
    {
        $posts =Post::where('status', Product::ACTIVE)->paginate(5);
        return view('frontend.posts.list', compact('posts'));
    }
    
    public function show()
    {
        $post = Post::findOrFail(request()->id);

        return view('frontend.posts.show', compact('post'));
    }

}

tét/app/Http/Controllers/Frontend/ProvinceController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Model\Bill;

use App\Http\Controllers\Controller;
use App\Model\Cart;
use App\Model\Product;
use App\Model\Province;
use App\Services\ProductService;
use App\Traits\InventoryTrait;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use RealRashid\SweetAlert\Facades\Alert;

class ProvinceController extends Controller
{
    public function list()
    {
        return response()->json([
            'provinces' => Province::all(),
        ], 200);
    }
}

tét/resources/views/frontend/cart/index.blade.php
@extends('frontend.frontend-layout')

@section('content')
    <!-- Shopping Cart -->
    <div class="shopping-cart section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Shopping Summery -->
                    <table class="table shopping-summery">
                        <thead>
                        <tr class="main-hading">
                            <th>Sản phẩm</th>
                            <th>Tên</th>
                            <th class="text-center">Giá tiền</th>
                            <th class="text-center">Số lượng</th>
                            <th class="text-center">Tổng tiền</th>
                            <th class="text-center"><i
                                    class="ti-trash remove-icon"></i></th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($cart->products as $product)
                            <tr>
                                <td class="image" data-title="No">
                                    <a href="{{ route('fr.product.show',
                                        ['slug' => $product->slug, 'id' => $product->id]) }}">
                                        <img
                                            src="{{ $product->image_full_path }}"
                                            alt="#">
                                    </a>

                                </td>
                                <td class="product-des"
                                    data-title="Description">
                                    <p class="product-name"><a
                                            href="#">{{$product->name}}</a></p>
                                </td>
                                <td class="price" data-title="Price">{{-- <span>{{number_format($product->price)}} ₫</span> --}}
                                    <span class="discount">{{ number_format($product->price_after_discount) }} đ</span>
                                 
                                </td>
                                <td class="qty" data-title="Qty">
                                    <!-- Input Order -->
                                    <div class="input-group">
                                        <div class="button minus">
                                            <form
                                                action="{{ route('fr.cart.decrease_product') }}"
                                                method="post">
                                                @csrf
                                                <input type="hidden"
                                                       name="cart_id"
                                                       value="{{ $cart->id }}">
                                                <input type="hidden"
                                                       name="product_id"
                                                       value="{{ $product->id }}">
                                                <button type="submit"
                                                        class="btn btn-primary"
                                                        data-type="minus">
                                                    <i class="ti-minus"></i>
                                                </button>
                                            </form>
                                        </div>
                                        <input type="text" name="quant[1]"
                                               class="input-number"
                                               disabled
                                               data-min="1" data-max="100"
                                               value="{{$product->pivot->quantity}}">
                                        <div class="button plus">
                                            <form
                                                action="{{ route('fr.cart.increase_product') }}"
                                                method="post">
                                                @csrf
                                                <input type="hidden"
                                                       name="cart_id"
                                                       value="{{ $cart->id }}">
                                                <input type="hidden"
                                                       name="product_id"
                                                       value="{{ $product->id }}">
                                                <button type="submit"
                                                        class="btn btn-primary"
                                                        data-field="quant[1]">
                                                    <i class="ti-plus"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                    <!--/ End Input Order -->
                                </td>
                                <td class="total-amount" data-title="Total">
                                    <span>{{ number_format($product->getTotalPrice()) }}</span>
                                </td>
                                <td class="action" data-title="Remove">
                                    <form
                                        action="{{ route('fr.cart.delete_product') }}"
                                        method="post">
                                        @csrf
                                        @method('delete')
                                        <input type="hidden"
                                               name="cart_id"
                                               value="{{ $cart->id }}">
                                        <input type="hidden"
                                               name="product_id"
                                               value="{{ $product->id }}">
                                        <button type="submit"
                                                class="bg-transparent border-0">
                                            <i class="ti-trash remove-icon"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @empty
                            Không có sản phẩm trong giỏ hàng
                        @endforelse
                        </tbody>
                    </table>
                    <!--/ End Shopping Summery -->
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- Total Amount -->
                    <input type="hidden" name="cart_id"
                           value="{{ $cart->id }}">
                    <div class="total-amount">
                        <div class="row">
                            <div class="col-lg-8 col-md-5 col-12">
                            </div>
                            <div class="col-lg-4 col-md-7 col-12">
                                <div class="right">
                                    <ul>
                                        <li>Tạm tính<span>{{ number_format($cart->subTotal()) }} ₫</span>
                                        <li class="last">Thành tiền<span>{{ number_format($cart->subTotal()) }} ₫</span></li>
                                    </ul>
                                    <div class="button5">
                                        <button
                                            type="button"
                                            @if(!$cart->products->count())
                                            disabled
                                            @endif
                                            id="btnCheckout"
                                            class="btn">
                                            Tiến hành đặt hàng
                                        </button>
                                        <a href="{{route('fr.home')}}"
                                           class="btn">Mua thêm sản phâm</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/ End Total Amount -->
                </div>
            </div>
        </div>
    </div>
    <!--/ End Shopping Cart -->
    <input type="hidden" id="cartId" value="{{$cart->id}}">
    @include('frontend.modals.checkout')
    <input type="hidden" value="{{ json_encode($userAddress) }}" id="shippingCharge">
@endsection
@push('javascripts')
    <script>
        $(document).on('click', '#btnCheckout', function (e) {
            e.preventDefault();
            let cartId = $('#cartId').val();
            $('#checkoutForm').append(`<input type="hidden" value="${ cartId }" name="cart_id"/>`)
            $('#checkoutModal').modal('show');
        });
    </script>
@endpush